/* Generated By:JavaCC: Do not edit this line. CalculatorConstants.java */
package program;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int AFFICHER = 14;
  /** RegularExpression Id. */
  int SIN = 15;
  /** RegularExpression Id. */
  int COS = 16;
  /** RegularExpression Id. */
  int SQRT = 17;
  /** RegularExpression Id. */
  int ID = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"afficher\"",
    "\"sin\"",
    "\"cos\"",
    "\"racine\"",
    "<ID>",
  };

}
